name: project_plant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:  
  animated_bottom_navigation_bar:  
  flutter_launcher_icons: ^0.14.2
  page_transition:
  sqflite: ^2.4.1
  intl: ^0.20.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  styled_widget: ^0.4.1
  responsive_framework: ^1.5.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

